### ISSUE TITLE
Negative float literals incorrectly parsed

### ISSUE THREAD

**Issue by adri326** [brundonsmith/rust_lisp#11]
Hello and thank you for this crate :)

As I was using it, I realized that writing negative floating-point number literals resulted in two (incorrect) arguments being produced instead. Looking at it, it looks like the integer part of the number is interpreted as a negative integer, whereas the floating part is interpreted as an integer literal:

```lisp
(debug -1.2)
```

**Expected:** `[Value::Float(-1.2)]`

**Actual:** `[Value::Int(-1), Value::Int(2)]`

I haven't yet looked into the source code as for the reason why they get incorrectly parsed, but I'll have the time to do so and try to fix it by myself in three to four weeks.

**Comment by brundonsmith** [comment]
I believe the commit I made above fixes the issue. Thanks for the bug report!

**Comment by adri326** [comment]
That did the trick, yes; I do have another issue with closures but I'll open another issue for that
