### ISSUE TITLE
`map` causes a runtime error when called with nested lists

### ISSUE THREAD

**Issue by adri326** [brundonsmith/rust_lisp#14]
The following piece of code causes a RuntimeError:

```lisp
(map (lambda (x) x) (list (list 0 1) (list 2 3)))
```

**Expected:** `((0 1) (2 3))`
**Actual:** `Runtime error: Argument 0 is not callable`

This is likely caused by https://github.com/brundonsmith/rust_lisp/blob/master/src/default_environment.rs#L185

**Comment by brundonsmith** [comment]
Fixed in
https://github.com/brundonsmith/rust_lisp/commit/659dd0ddfaf514ce3d25eb039a624122b7be7723
