### ISSUE TITLE
(< 0 0.1)  evaluates to F

### ISSUE THREAD

**Issue by lasiotus** [brundonsmith/rust_lisp#28]
(< 0 0.1)  evaluates to F, while (<= 0 0.1) evaluates to T. I guess the second operand is cast to an integer, instead of the first operand getting cast to a float.

**Comment by brundonsmith** [comment]
Fixed in https://github.com/brundonsmith/rust_lisp/commit/c8d9cc849a625c71cb000adb0d04bfa8bc50b415
