### ISSUE TITLE
[Bug] Panic on trying to unwrap a `None` value (only relevant for crate version)

### ISSUE THREAD

**Issue by alexmozaidze** [brundonsmith/rust_lisp#3]
The following lisp code makes interpreter panic
```lisp
(defun lol () (+ 1 2))
(lol)
```
This doesn't panic
```lisp
(defun lol (a) (+ a 2))
(lol 1)
```

This is only present on crate version of this package, Github version is fine
I had to add the following lines in `Cargo.toml` in order to get latest version
```toml
[replace]
"rust_lisp:0.2.0" = { git = "https://github.com/brundonsmith/rust_lisp" }
```
Can you update the crate version?

**Comment by brundonsmith** [comment]
Yes, I'll update the crate

**Comment by brundonsmith** [comment]
Done
